CREATE TABLE IF NOT EXISTS "account" (
  "account_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "profile_pic_name" varchar(30),
  "profile_pic" bytea,
  "first_name" varchar(30) NOT NULL,
  "last_name" varchar(30) NOT NULL,
  "email" varchar NOT NULL,
  "password_hash" varchar NOT NULL,
  "salt" varchar,
  "create_time" timestamp DEFAULT (now()),
  "update_time" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "brand" (
  "brand_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(30) NOT NULL,
  "create_time" timestamp DEFAULT (now()),
  "update_time" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "subscription" (
  "subscription_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "brand_id" int NOT NULL,
  "account_id" int NOT NULL,
  "create_time" timestamp DEFAULT (now()),
  "update_time" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "sale_item" (
  "sale_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "brand_id" int NOT NULL,
  "name" varchar(30) NOT NULL,
  "description" text,
  "item_variation_id" int NOT NULL,
  "url"
  "create_time" timestamp DEFAULT (now()),
  "update_time" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "size" (
  "size_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(15) NOT NULL,
  "create_time" timestamp DEFAULT (now()),
  "update_time" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "gender" (
  "gender_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(10) NOT NULL,
  "create_time" timestamp DEFAULT (now()),
  "update_time" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "clothing_article" (
  "clothing_article_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(25) NOT NULL,
  "create_time" timestamp DEFAULT (now()),
  "update_time" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "color" (
  "color_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(25) NOT NULL,
  "color_category_id" int,
  "create_time" timestamp DEFAULT (now()),
  "update_time" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "color_category" (
  "color_category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "color" varchar(20) NOT NULL,
  "create_time" timestamp DEFAULT (now()),
  "update_time" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "item_variation" (
  "item_variation_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "color_id" int,
  "clothing_article_id" int,
  "gender_id" int,
  "size_id" int,
  "sale_price" money NOT NULL,
  "original_price" money,
  "is_sale" bool NOT NULL DEFAULT true,
  "image_name" varchar(30),
  "image" bytea,
  "sale_end_time" timestamp DEFAULT null,
  "create_time" timestamp DEFAULT (now()),
  "update_time" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "list" (
  "list_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "list_image_name" varchar(30),
  "list_image" bytea,
  "name" varchar(25),
  "description" text,
  "account_id" int,
  "create_time" timestamp DEFAULT (now()),
  "update_time" timestamp DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "list_item" (
  "list_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "list_id" int NOT NULL,
  "sale_item_id" int NOT NULL
);

ALTER TABLE "subscription" ADD FOREIGN KEY ("brand_id") REFERENCES "brand" ("brand_id");

ALTER TABLE "subscription" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("account_id");

ALTER TABLE "sale_item" ADD FOREIGN KEY ("brand_id") REFERENCES "brand" ("brand_id");

ALTER TABLE "sale_item" ADD FOREIGN KEY ("item_variation_id") REFERENCES "item_variation" ("item_variation_id");

ALTER TABLE "color" ADD FOREIGN KEY ("color_category_id") REFERENCES "color_category" ("color_category_id");

ALTER TABLE "item_variation" ADD FOREIGN KEY ("color_id") REFERENCES "color" ("color_id");

ALTER TABLE "item_variation" ADD FOREIGN KEY ("clothing_article_id") REFERENCES "clothing_article" ("clothing_article_id");

ALTER TABLE "item_variation" ADD FOREIGN KEY ("gender_id") REFERENCES "gender" ("gender_id");

ALTER TABLE "item_variation" ADD FOREIGN KEY ("size_id") REFERENCES "size" ("size_id");

ALTER TABLE "list" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("account_id");

ALTER TABLE "list_item" ADD FOREIGN KEY ("list_id") REFERENCES "list" ("list_id");

ALTER TABLE "list_item" ADD FOREIGN KEY ("sale_item_id") REFERENCES "sale_item" ("sale_item_id");


INSERT INTO _USER (ID, FIRST_NAME, LAST_NAME)
VALUES (1, 'John', 'Doe');

INSERT INTO _USER (ID, FIRST_NAME, LAST_NAME)
VALUES (2, 'Alice', 'Wonderland');


INSERT INTO brand(name) 
VALUES
  ('Uniqlo'),
  ('Madewell'),
  ('luluLemon'),
  ('Nike'),
  ('Patagonia'),
  ('Club Monoco'),
  ('Aritzia');

INSERT INTO gender(name) 
VALUES
  ('Women'),
  ('Men'),
  ('Unisex'),
  ('Girls'),
  ('Boys');

INSERT INTO color_category(color) 
VALUES
  ('Red'),
  ('Blue'),
  ('Yellow'),
  ('Green'),
  ('Orange'),
  ('Purple'),
  ('Brown'),
  ('White'),
  ('Black'),
  ('Grey'),
  ('Beige'),
  ('Pink'),
  ('Multi');

INSERT INTO size(name) 
VALUES 
('XXXS'),
('XXS'),
('XS'),
('S'),
('M'),
('L'),
('XL'),
('XXL'),
('XXXL'),
('ONE SIZE'),
('2'),
('4'),
('6'),
('8'),
('10'),
('12'),
('14'),
('16'),
('18'),
('20'),
('22'),
('24'),
('26'),
('30A'),
('30B'),
('30C'),
('30D'),
('30DD'),
('30DDD'),
('30G'),
('32AA'),
('32A'),
('32B'),
('32C'),
('32D'),
('32DD'),
('32DDD'),
('32G'),
('34AA'),
('34A'),
('34B'),
('34C'),
('34D'),
('34DD'),
('34DDD'),
('34G'),
('36AA'),
('36A'),
('36B'),
('36C'),
('36D'),
('36DD'),
('36DDD'),
('36G'),
('36AA'),
('36A'),
('36B'),
('36C'),
('36D'),
('36DD'),
('36DDD'),
('36G'),
('38AA'),
('38A'),
('38B'),
('38C'),
('38D'),
('38DD'),
('38DDD'),
('38G'),
('40AA'),
('40A'),
('40B'),
('40C'),
('40D'),
('40DD'),
('40DDD'),
('40G'),
('42AA'),
('42A'),
('42B'),
('42C'),
('42D'),
('42DD'),
('42DDD'),
('42G'),
('23'),
('24'),
('25'),
('26'),
('27'),
('28'),
('29'),
('30'),
('32'),
('33'),
('34'),
('35'),
('36'),
('37'),
('38'),
('39'),
('40'),
('41'),
('42'),
('43'),
('44'),
('45'),
('46'),
('47'),
('48'),
('49'),
('50'),
('51'),
('52'),
('53'),
('54'),
('55'),
('56'),
('57'),
('58'),
('59'),
('60'),
('61'),
('62'),
('63'),
('64'),
('65'),
('66'),
('62'),
('62'),
('1'),
('1.5'),
('2.5'),
('3'),
('3.5'),
('4.5'),
('5'),
('5.5'),
('6.5'),
('7'),
('7.5'),
('8.5'),
('9'),
('9.5'),
('10.5'),
('11'),
('11.5'),
('12.5'),
('13'),
('13.5'),
('14.5'),
('15'),
('15.5'),
('16.5'),
('17'),
('17.5'),
('18.5'),
('19'),
('19.5'),
('20.5'),
('21'),
('21.5'),
('22.5'),
('1Y'),
('1.5Y'),
('2Y'),
('2.5Y'),
('3'),
('3.5Y'),
('4'),
('4.5Y'),
('5Y'),
('5.5Y'),
('6Y'),
('6.5Y'),
('7Y'),
('8C'),
('9C'),
('10C'),
('10.5C'),
('11C'),
('11.5C'),
('12C'),
('12.5C'),
('13C'),
('13.5C'),
('1C'),
('2C'),
('3C'),
('4C'),
('5C'),
('6C'),
('7C'),
('0-6M'),
('6-12M'),
('12-24M'),
('24-36M'),
('3-4.5'),
('4-5'),
('5-7'),
('7-9'),
('9-11'),
('2C-3C'),
('3C-7C'),
('7C-10C'),
('10C-3Y'),
('3Y-5Y'),
('5Y-7Y');


INSERT INTO clothing_article(name) 
VALUES 
('Jewelry'),
('Bag'),
('Accessory'),
('Shoes'),
('Top'),
('Bottom');
